### ISSUE TITLE
[Bug] panic on vm status check in debug mode

### ISSUE THREAD

**Issue by lerencao** [diem/diem#8597] opened 2021-06-22 11:51 UTC
# 🐛 Bug

**Stack trace/error message**
```
details: panicked at 'Unexpected offsets. major_status: OUT_OF_GAS sub_status: None location: Undefined offsets: []', 
/Users/xxxx/.cargo/git/checkouts/diem-5aa6d6b8b0487904/c7b8dc2/language/vm/src/errors.rs:69:17
backtrace:    0:        0x108df227a - backtrace::backtrace::libunwind::trace::h261d6410e683f50c
```

It seems that the debug_assert on the pic should be removed.

![image](https://user-images.githubusercontent.com/1456096/122919683-1a4f7400-d393-11eb-8459-f9e1b510d0f0.png)

**Comment by bob-wilson** [comment] 2021-06-23 17:19
I believe this is a duplicate of #7614. I started looking into a fix a few months ago (see #7777) but didn't come up with anything very satisfactory.

**Closed by bob-wilson** 2021-06-23 17:19 UTC
Labels: bug
