### ISSUE TITLE
> # 🐛 Bug

### ISSUE THREAD

**Issue by syam585** [diem/diem#7333] opened 2021-01-22 23:23 UTC
> # 🐛 Bug
> Hello I tried to add 10,000 Coin1 in Reference Wallet to test the function, but got nothing after I clicking the confirm button. The message showed on the frontend told me my request was successful, but I found there were error messages in backend output.
> 
> I tried to check codes of this function to learn what happened, and found that `BalanceError` only prevents the cover process code from executing, but payment charge has already finished at that time. Here is what I learn:
> 
> * In `backend/wallet/services/order.py`, `execute_trade()` first checks whether the inventory account has enough balance, and buys from LP if not.
> * Then it tries to process internal transaction. In `internal_transaction()`, the second balance check is executed, and the function raises `BalanceError` exception if not.
> * The `execute_trade()` function catches the exception, updates database table, and returns a `False`.
> * In `execute_order()`, `cover_order()` function is skipped since we get a `False` from `execute_trade()`.
> * But, the outer `process_order()` function and `ExecuteQuoteView` class never handle the exception, and the latter class responses a HTTP 200 to the frontend.
> 
> ## Steps to reproduce
> 1. Click "transfer" button
> 2. Click "add" button
> 3. Add 10,000 Coin1
> 4. Click "review" button
> 5. Click "confirm" button
> 6. A successful message is showed, but no Coin1 got
> 
> ## Error messages
> ```
> backend-worker_1         | Traceback (most recent call last):
> backend-worker_1         |   File "./wallet/services/order.py", line 182, in execute_trade
> backend-worker_1         |     payment_type=TransactionType.INTERNAL,
> backend-worker_1         |   File "./wallet/services/transaction.py", line 349, in internal_transaction
> backend-worker_1         |     f"Balance {account_service.get_account_balance_by_id(account_id=sender_id).total[currency]} "
> backend-worker_1         | wallet.types.BalanceError: Balance 7001000000 is less than amount needed 10000000000
> ```
> 
> ## Expected Behavior
> Correctly add the balance after confirming the transfer, or show a error message to the user.
> 
> ## System information
> Ubuntu 18.04

_Originally posted by @syam585 in https://github.com/diem/reference-wallet/issues/14#issuecomment-762223899_

**Comment by yanivmo** [comment] 2021-03-09 16:44
This is a duplicate of diem/reference-wallet#14. Should be closed here.

**Closed** 2021-03-10 18:55 UTC
