### ISSUE TITLE
[Feature Request] `struct spec` that can refer to global state

### ISSUE THREAD

**Issue by sblackshear** [diem/diem#7471] opened 2021-02-03 01:46 UTC
I want to say "Type `T` can only be packed when `e` holds" (where `e` is a predicate involving global storage). I tried to do this with a spec struct invariant, but these are not allowed to refer to global storage. Is there another way?
```
struct EphemeralCap<T> {
  issuer: address,
  holder: address,
}
public fun is_revoked<T>(a: address): bool acquires Cap, CapIssuer {
    let cap = borrow_global<Cap<T>>(a);
    let cap_issuer = borrow_global<CapIssuer<T>>(cap.issuer);
    cap_issuer.time >= cap.validity_timestamp
}
/// EphemeralCap<T>'s can only be created by an account with a valid `Cap<T>`
spec struct EphemeralCap {
    // TODO: prover doesn't let data invariants depend on global state, so not sure how to state this
    // TODO: ideally, this would be an `invariant pack` --it's ok if the Cap<T> is revoked after the
    // EphemeralCap<T> is created.
    invariant !is_revoked<T>(issuer);
}
```

**Comment by wrwg** [comment] 2021-04-02 21:42
There are multiple issues with the soundness of this. What happens if is_revoked changes after pack? Need to investigate.

**Comment by wrwg** [comment] 2021-04-02 21:44
Note that you could do this with a global invariant put not at pack time but for stored resources. Would that be enough for this use case?

**Comment by wrwg** [comment] 2021-05-13 18:18
Closing as this is by design. Feel free to re-open if you want to continue to discuss.

**Closed by wrwg** 2021-05-13 18:18 UTC
